### ISSUE TITLE
train.py giving index error

### ISSUE THREAD

**Issue by ArmaanBhullar** [facebookresearch/mixup-cifar10#13]
Hi,
I was trying to run your code,
Exact command being:
$ CUDA_VISIBLE_DEVICES=0 python train.py --lr=0.1 --seed=20170922 --decay=1e-4
Before running the command I modified train.py to make download=True in both trainset and testset.
I got the following output:
_==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
==> Building model..
1
Using CUDA..

Epoch: 0
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    train_loss, reg_loss, train_acc = train(epoch)
  File "train.py", line 165, in train
    train_loss += loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number_

Could you help as to what I'm doing wrong? I ran the debugger then, it errors out here: 
  _File "train.py", line 165, in train
    train_loss += loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number_

**Comment by maggiezha** [comment]
I got this IndexError as well, have you figured it out?

**Comment by maggiezha** [comment]
this can solve the problem: https://discuss.pytorch.org/t/this-will-be-an-error-in-pytorch-0-5/19691

**Comment by dedekinds** [comment]
`train_loss+=loss.data[0]`
---->
`train_loss+=loss.item()`
